/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import connection.MysqlConnection;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {
    public static String regexEmail = "^[A-Za-z0-9+_.-]+@gmail(.+)$";
    public static boolean c = false;
    /**
     * Creates new form LoginForm
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Đăng nhập");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        cbselect = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        showPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(71, 31, 61));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/globe.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(186, 79, 84));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setBackground(new java.awt.Color(186, 79, 84));
        username.setForeground(new java.awt.Color(187, 187, 187));
        username.setText("Example@gmail.com");
        username.setToolTipText("");
        username.setBorder(null);
        username.setDisabledTextColor(new java.awt.Color(187, 187, 187));
        username.setDoubleBuffered(true);
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 202, 36));

        password.setBackground(new java.awt.Color(186, 79, 84));
        password.setForeground(new java.awt.Color(187, 187, 187));
        password.setText("password");
        password.setToolTipText("");
        password.setBorder(null);
        password.setDisabledTextColor(new java.awt.Color(187, 187, 187));
        password.setDoubleBuffered(true);
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 170, 29));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setToolTipText("");
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 200, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 200, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 20, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlock.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 20, 30));

        btnSubmit.setBackground(new java.awt.Color(255, 204, 51));
        btnSubmit.setText("SIGN IN");
        btnSubmit.setToolTipText("");
        btnSubmit.setActionCommand("");
        btnSubmit.setBorder(null);
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel3.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 120, 40));

        cbselect.setBackground(new java.awt.Color(186, 79, 84));
        cbselect.setEditable(true);
        cbselect.setForeground(new java.awt.Color(204, 204, 204));
        cbselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Admin", "User" }));
        cbselect.setBorder(null);
        cbselect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(cbselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 200, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/role.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 204, 20, 30));

        showPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hidden.png"))); // NOI18N
        showPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPassMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showPassMousePressed(evt);
            }
        });
        jPanel3.add(showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 30, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(cbselect.getSelectedIndex() == 0 || username.getText().equals("") || String.valueOf(password.getPassword()).equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
        }
        else if(cbselect.getSelectedIndex() == 1)
        {
            try {
            Connection connection = MysqlConnection.getMysqlConnection();
            String Sql = "select * from adminacc where adusername = ? and adpassword = ?";
            PreparedStatement ps = connection.prepareCall(Sql);
            ps.setString(1, username.getText());
            ps.setString(2, String.valueOf(password.getPassword()));
            ResultSet rs =  ps.executeQuery();
            
            if(username.getText().equals("") ||String.valueOf(password.getPassword()).equals(""))
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            else if(!username.getText().matches(regexEmail))
            {
                JOptionPane.showMessageDialog(this, "Email không đúng định dạng");
            }
            else if(rs.next())
            {
                this.setVisible(false);
                new AdminPage().setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không đúng");
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e){
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
    }
        else
        {
             if(username.getText().equals("") || String.valueOf(password.getPassword()).equals(""))
            {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
                }
           
            try {
                FileReader Fis = new FileReader("userACC.txt");
                BufferedReader Bfr = new BufferedReader(Fis);
                String line = "";


                while(true)
                {
                    line = Bfr.readLine();
                    if(line  == null){
                        JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không đúng");
                        break;
                    }
                    String Username[] = line.split("-");
                    if(username.getText().equals("") ||String.valueOf(password.getPassword()).equals(""))
                    {
                        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
                        break;
                    }
                    else if(!username.getText().matches(regexEmail))
                    {
                        JOptionPane.showMessageDialog(this, "Email không đúng định dạng");
                        break;
                    }
                    else if(Username[0].equals(username.getText()) && Username[1].equals(String.valueOf(password.getPassword())))
                    {              
                        try {
                            this.dispose();
                            new UserPage().setVisible(true);
                            break;
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void showPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPassMouseClicked
      password.setEchoChar('*');
    }//GEN-LAST:event_showPassMouseClicked

    private void showPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPassMousePressed
        password.setEchoChar((char)0);
    }//GEN-LAST:event_showPassMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbselect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JPasswordField password;
    private javax.swing.JLabel showPass;
    public static javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
