/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.AdminPage;

import controllers.HoDanModify;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class HoDan extends javax.swing.JPanel {
DefaultTableModel tableModel;

    List<models.HoDan> hoDanList = new ArrayList<>();
    /**
     * Creates new form HoDan
     */
    public HoDan() {
        initComponents();
        tableModel = (DefaultTableModel) tblHoDan.getModel();
        showHoDan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoDan = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        btnQuanLy = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(590, 442));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Hộ dân trong khu phố");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblHoDan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ID hộ dân", "Số thành viên", "Số nhà", "Tài khoản", "Mật khẩu"
            }
        ));
        tblHoDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoDanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoDan);

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnQuanLy.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnQuanLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quanly_hodan.png"))); // NOI18N
        btnQuanLy.setText("Quản lý hộ dân");
        btnQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnQuanLy)
                        .addGap(274, 274, 274)
                        .addComponent(btnTimKiem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(179, 179, 179))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblHoDanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoDanMouseClicked
        int index = tblHoDan.getSelectedRow();

        Admin_ChiTietHoDan chitiet = new Admin_ChiTietHoDan(Integer.parseInt(tableModel.getValueAt(index,0).toString()));

        String idHo =  tableModel.getValueAt(index,0).toString();
        String soNha =  tableModel.getValueAt(index,3).toString();
        String soTV =  tableModel.getValueAt(index,2).toString();
        String taiKhoan =  tableModel.getValueAt(index,3).toString();
        String matKhau =  tableModel.getValueAt(index,4).toString();

        chitiet.setVisible(true);
        chitiet.pack();
        chitiet.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        chitiet.txtIdHo.setText(idHo);
        chitiet.txtSoNha.setText(soNha);
        chitiet.txtSoTV.setText(soTV);
        chitiet.txtTaiKhoan.setText(taiKhoan);
        chitiet.txtMatKhau.setText(matKhau);

    }//GEN-LAST:event_tblHoDanMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập số nhà muốn tìm kiếm");
        if (input != null && input.length() > 0) {
            hoDanList = HoDanModify.timKiemTheoSoNha(input);

            tableModel.setRowCount(0);

            hoDanList.forEach(hoDan -> {
                tableModel.addRow(new Object[]{tableModel.getRowCount() + 1, hoDan.getIdHo(), hoDan.getSoThanhVien(),
                    hoDan.getSoNha(), hoDan.getTaiKhoan(), hoDan.getMatKhau()});
        });
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập số nhà");
            showHoDan();
        }
        if(tableModel.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Số nhà '"+input+"' không tồn tại");
            showHoDan();
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyActionPerformed
        // TODO add your handling code here:
        Admin_QuanLyHoDan qlhd = new Admin_QuanLyHoDan();
        qlhd.setVisible(true);

        qlhd.pack();
        qlhd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnQuanLyActionPerformed
private void showHoDan() {
        hoDanList = HoDanModify.findAll();

        tableModel.setRowCount(0);

        hoDanList.forEach(hoDan -> {
            tableModel.addRow(new Object[]{tableModel.getRowCount() + 1, hoDan.getIdHo(), hoDan.getSoThanhVien(),
                hoDan.getSoNha(), hoDan.getTaiKhoan(), hoDan.getMatKhau()});
        });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuanLy;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHoDan;
    // End of variables declaration//GEN-END:variables
}
