/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.UserPage;
import java.sql.*;
import connection.MysqlConnection;
import java.util.logging.Level;
import java.util.logging.Logger;
import view.AdminPage.SendEmailJPanel;

/**
 *
 * @author ASUS
 */
public class TrangChuUser extends javax.swing.JPanel {

    /**
     * Creates new form TrangChuJPanel
     */
    public TrangChuUser() throws ClassNotFoundException {
        initComponents();
        showData();
        nk();
        hk();
    }
public void showData(){
        Connection connection;
        try {

            connection = MysqlConnection.getMysqlConnection();
            String Sql_tv = "SELECT*FROM thanhvien";
            String Sql_hodan = "SELECT*FROM hodan";
            PreparedStatement ps1 = connection.prepareStatement(Sql_tv);
            ResultSet rs1 = ps1.executeQuery();
            
            PreparedStatement ps2 = connection.prepareStatement(Sql_hodan);
            ResultSet rs2 = ps2.executeQuery();

            while (rs1.next()) {
                soNhanKhau.setText(String.valueOf(rs1.getRow()));
            }
            while (rs2.next()) {
                soHoDan.setText(String.valueOf(rs2.getRow()));
            }

        } catch (SQLException ex) {
            Logger.getLogger(SendEmailJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SendEmailJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.
     * The content of this method is always
 regenerated by the Form Editor.
     * @throws java.lang.ClassNotFoundException
     */
     public void nk() throws ClassNotFoundException{
        String query="select count(*) as tong from thanhvien ";
		try {
			Connection conn=MysqlConnection.getMysqlConnection();
			Statement st=conn.createStatement();
			ResultSet rs=st.executeQuery(query);			
			if(rs.next()) {
                            String t=String.valueOf(rs.getInt("tong"));
				soNhanKhau.setText(t);
			}
                       // else txtNk.setText("abc");
		}catch(SQLException e) {
			
		}
    }   
     public void hk() throws ClassNotFoundException{
        String query="select count(*) as tong from hodan ";
		try {
			Connection conn=MysqlConnection.getMysqlConnection();
			Statement st=conn.createStatement();
			ResultSet rs=st.executeQuery(query);			
			if(rs.next()) {
                            String t=String.valueOf(rs.getInt("tong"));
				soHoDan.setText(t);
			}
                       // else txtNk.setText("abc");
		}catch(SQLException e) {
			
		}
    }   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soHo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        soHoDan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        soNhanKhau = new javax.swing.JLabel();

        soHo.setBackground(new java.awt.Color(255, 0, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hộ khẩu trên địa bàn");

        soHoDan.setBackground(new java.awt.Color(255, 255, 255));
        soHoDan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        soHoDan.setForeground(new java.awt.Color(255, 255, 255));
        soHoDan.setText("?");

        javax.swing.GroupLayout soHoLayout = new javax.swing.GroupLayout(soHo);
        soHo.setLayout(soHoLayout);
        soHoLayout.setHorizontalGroup(
            soHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soHoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(soHoDan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        soHoLayout.setVerticalGroup(
            soHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, soHoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(22, 22, 22))
            .addGroup(soHoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(soHoDan)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 0, 102));
        jPanel3.setForeground(new java.awt.Color(255, 0, 0));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/globe.png"))); // NOI18N
        jLabel5.setText("jLabel1");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nhân khẩu trên địa bàn");

        soNhanKhau.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        soNhanKhau.setForeground(new java.awt.Color(255, 255, 255));
        soNhanKhau.setText("?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(soNhanKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(398, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soNhanKhau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(soHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(soHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel soHo;
    private javax.swing.JLabel soHoDan;
    private javax.swing.JLabel soNhanKhau;
    // End of variables declaration//GEN-END:variables
}
